namespace sisops {
    const int PAGE_SIZE = 16;
    const int REAL_MEMORY_SIZE = 2048;
    const int SWAPPING_MEMORY_SIZE = 4096;
    const int REAL_MEMORY_PAGE_AMOUNT = REAL_MEMORY_SIZE / PAGE_SIZE;
    const int SWAPPING_MEMORY_PAGE_AMOUNT = SWAPPING_MEMORY_SIZE / PAGE_SIZE;
}